import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const therapists = [
  {
    slug: 'susan-smith',
    imageUrl: '/avatars/susan-smith.jpg',
    published: true,
    name: 'Dr. Susan Smith',
    primaryCredential: 'PhD',
    primaryCredentialAlt: 'LPCC',
    gender: 'Female',
    phone: '310-555-1234',
    workEmail: 'susan.smith@therapyco.com',
    website: 'https://www.susansmiththerapy.com',
    primaryAddress: '1234 Sunset Blvd',
    primaryCity: 'Los Angeles',
    primaryState: 'CA',
    primaryZip: '90026',
    telehealth: true,
    inPerson: true,
    locationDescription: 'Offers both virtual sessions and in-office appointments in Echo Park',
    seoZip1: '90026',
    seoZip2: '90027',
    nearbyCity1: 'Burbank',
    feeIndividual: '150',
    feeCouples: '200',
    slidingScale: false,
    freeConsultation: true,
    paymentMethods: ['Credit Card', 'Cash', 'Venmo'],
    insuranceAccepted: 'Aetna, Blue Cross',
    licenseStatus: 'Active',
    profession: 'Licensed Psychologist',
    licenseNumber: 'PSY123456',
    licenseState: 'CA',
    licenseExpirationMonth: 12,
    licenseExpirationYear: 2025,
    educationSchool: 'UCLA',
    educationDegree: 'PhD Clinical Psychology',
    educationYearGraduated: 2010,
    practiceStartYear: 2011,
    tagline: 'Empowering you to find balance and resilience',
    personalStatement1: 'I take a strengths-based approach, helping clients build on what already works.',
    personalStatement2: 'My passion lies in guiding individuals through life transitions and trauma recovery.',
    personalStatement3: 'Together we’ll craft a personalized plan that honors your values and goals.',
    issues: ['Anxiety', 'Depression', 'Trauma'],
    specialtyDescription: 'Specializes in CBT for mood disorders and PTSD.',
    mentalHealthRoles: ['Therapist', 'Clinical Supervisor'],
    sexuality: 'All',
    ages: ['Adult', 'Older Adult'],
    participants: ['Individual', 'Couples'],
    communities: ['LGBTQ+'],
    languages: ['English', 'Spanish'],
    topIssues: ['Stress', 'Relationship Issues'],
    treatmentStyle: ['CBT', 'Mindfulness'],
    treatmentStyleDescription: 'Integrative CBT blended with mindfulness exercises.',
  },
  {
    slug: 'michael-jones',
    imageUrl: '/avatars/michael-jones.jpg',
    published: true,
    name: 'Michael Jones, LCSW',
    primaryCredential: 'LCSW',
    gender: 'Male',
    phone: '415-555-5678',
    workEmail: 'michael.jones@healwell.com',
    website: 'https://www.healwell.com/michael-jones',
    primaryCity: 'San Francisco',
    primaryState: 'CA',
    telehealth: true,
    inPerson: false,
    locationDescription: '100% virtual practice serving clients statewide in California',
    seoZip1: '94102',
    nearbyCity1: 'Oakland',
    feeIndividual: '120',
    slidingScale: true,
    freeConsultation: false,
    paymentMethods: ['Credit Card', 'PayPal'],
    insuranceAccepted: 'Cigna, UnitedHealthcare',
    licenseStatus: 'Active',
    profession: 'Licensed Clinical Social Worker',
    licenseNumber: 'LCSW789012',
    licenseState: 'CA',
    licenseExpirationMonth: 6,
    licenseExpirationYear: 2026,
    educationSchool: 'USF',
    educationDegree: 'MSW',
    educationYearGraduated: 2015,
    practiceStartYear: 2016,
    tagline: 'Transforming challenges into growth opportunities',
    personalStatement1: 'I foster a collaborative space where healing begins with understanding.',
    personalStatement2: 'Trauma-informed care is at the core of my practice.',
    personalStatement3: 'Let’s work together to achieve lasting change.',
    issues: ['PTSD', 'Grief', 'Addiction'],
    specialtyDescription: 'Expert in trauma recovery and substance-use counseling.',
    mentalHealthRoles: ['Therapist', 'Group Facilitator'],
    sexuality: 'All',
    ages: ['Adult'],
    participants: ['Individual', 'Group'],
    communities: ['Veterans'],
    languages: ['English'],
    topIssues: ['Trauma', 'Addiction Recovery'],
    treatmentStyle: ['EMDR', 'DBT'],
    treatmentStyleDescription: 'EMDR for trauma processing, DBT for emotional regulation.',
  },
  {
    slug: 'linda-chen',
    imageUrl: '/avatars/linda-chen.jpg',
    published: true,
    name: 'Linda Chen, PsyD',
    primaryCredential: 'PsyD',
    gender: 'Female',
    phone: '619-555-9101',
    workEmail: 'linda.chen@mindpath.com',
    website: 'https://www.mindpath.com/linda-chen',
    primaryCity: 'San Diego',
    primaryState: 'CA',
    additionalCity: 'La Jolla',
    telehealth: true,
    inPerson: true,
    locationDescription: 'In-person in La Jolla & virtual statewide',
    seoZip1: '92037',
    nearbyCity1: 'Chula Vista',
    feeIndividual: '175',
    feeCouples: '220',
    slidingScale: false,
    freeConsultation: true,
    paymentMethods: ['Debit Card', 'Credit Card'],
    insuranceAccepted: 'Blue Shield, Anthem',
    licenseStatus: 'Active',
    profession: 'Clinical Psychologist',
    licenseNumber: 'PSYD345678',
    licenseState: 'CA',
    licenseExpirationMonth: 11,
    licenseExpirationYear: 2025,
    educationSchool: 'Pepperdine',
    educationDegree: 'PsyD Clinical Psychology',
    educationYearGraduated: 2012,
    practiceStartYear: 2013,
    tagline: 'Supporting you to thrive, not just survive',
    personalStatement1: 'My goal is to help you rediscover hope and purpose.',
    personalStatement2: 'I blend relational and mindfulness-based therapies.',
    personalStatement3: 'Your well-being is my top priority.',
    issues: ['Depression', 'Anxiety'],
    specialtyDescription: 'Focus on women’s issues and perinatal mental health.',
    mentalHealthRoles: ['Therapist'],
    sexuality: 'All',
    ages: ['Adult'],
    participants: ['Individual'],
    communities: ['Women'],
    languages: ['English', 'Mandarin'],
    topIssues: ['Perinatal Mood Disorders'],
    treatmentStyle: ['Mindfulness', 'ACT'],
    treatmentStyleDescription: 'Mindfulness-based ACT for life transitions.',
  },
  {
    slug: 'david-khan',
    imageUrl: '/avatars/david-khan.jpg',
    published: true,
    name: 'David Khan, LMFT',
    primaryCredential: 'LMFT',
    gender: 'Male',
    phone: '916-555-2323',
    workEmail: 'david.khan@familyfirst.com',
    website: 'https://www.familyfirst.com/david-khan',
    primaryCity: 'Sacramento',
    primaryState: 'CA',
    telehealth: false,
    inPerson: true,
    locationDescription: 'Office located in Midtown Sacramento',
    seoZip1: '95816',
    nearbyCity1: 'Roseville',
    feeIndividual: '140',
    feeCouples: '180',
    slidingScale: true,
    freeConsultation: false,
    paymentMethods: ['Credit Card', 'Cash'],
    insuranceAccepted: 'Sliding scale only',
    licenseStatus: 'Active',
    profession: 'Marriage & Family Therapist',
    licenseNumber: 'LMFT901234',
    licenseState: 'CA',
    licenseExpirationMonth: 9,
    licenseExpirationYear: 2025,
    educationSchool: 'Stanford',
    educationDegree: 'MA Counseling Psychology',
    educationYearGraduated: 2014,
    practiceStartYear: 2015,
    tagline: 'Healing families, strengthening bonds',
    personalStatement1: 'I help couples and families navigate conflict with compassion.',
    personalStatement2: 'Solution-focused and systemic approaches drive my work.',
    personalStatement3: 'Let’s build healthier relationships together.',
    issues: ['Relationship Conflict', 'Parenting Challenges'],
    specialtyDescription: 'Experienced in family systems therapy.',
    mentalHealthRoles: ['Therapist', 'Supervisor'],
    sexuality: 'All',
    ages: ['Adult', 'Teens'],
    participants: ['Couples', 'Families'],
    communities: ['Military Families'],
    languages: ['English', 'Hindi'],
    topIssues: ['Communication Issues'],
    treatmentStyle: ['Family Systems', 'CBT'],
    treatmentStyleDescription: 'Family systems therapy integrated with CBT techniques.',
  },
  {
    slug: 'emily-park',
    imageUrl: '/avatars/emily-park.jpg',
    published: true,
    name: 'Emily Park, LPC',
    primaryCredential: 'LPC',
    gender: 'Female',
    phone: '323-555-4545',
    workEmail: 'emily.park@brightmind.com',
    website: 'https://www.brightmind.com/emily-park',
    primaryCity: 'Los Angeles',
    primaryState: 'CA',
    telehealth: true,
    inPerson: true,
    locationDescription: 'Near Downtown LA & fully virtual',
    seoZip1: '90014',
    nearbyCity1: 'Glendale',
    feeIndividual: '130',
    slidingScale: true,
    freeConsultation: true,
    paymentMethods: ['Cash', 'Credit Card'],
    insuranceAccepted: 'Most PPOs',
    licenseStatus: 'Active',
    profession: 'Licensed Professional Counselor',
    licenseNumber: 'LPC567890',
    licenseState: 'CA',
    licenseExpirationMonth: 4,
    licenseExpirationYear: 2026,
    educationSchool: 'USC',
    educationDegree: 'MA Counseling',
    educationYearGraduated: 2016,
    practiceStartYear: 2017,
    tagline: 'Guiding you toward a brighter tomorrow',
    personalStatement1: 'I focus on creating a warm, non-judgmental space.',
    personalStatement2: 'Together we’ll tackle anxiety and self-esteem issues.',
    personalStatement3: 'I believe small changes lead to big results.',
    issues: ['Anxiety', 'Self-Esteem'],
    specialtyDescription: 'Expert in life-stage transitions and self-worth.',
    mentalHealthRoles: ['Therapist'],
    sexuality: 'All',
    ages: ['Adolescents', 'Adult'],
    participants: ['Individual'],
    communities: ['Students'],
    languages: ['English', 'Korean'],
    topIssues: ['Life Transitions'],
    treatmentStyle: ['Solution-Focused', 'Narrative'],
    treatmentStyleDescription: 'Solution-focused therapy enhanced by narrative techniques.',
  },
  {
    slug: 'alex-rodriguez',
    imageUrl: '/avatars/alex-rodriguez.jpg',
    published: false,
    name: 'Alex Rodriguez, PsyD',
    primaryCredential: 'PsyD',
    gender: 'Non-binary',
    phone: '408-555-6767',
    workEmail: 'alex.rodriguez@openmind.com',
    website: 'https://www.openmindtherapy.com/alex-rodriguez',
    primaryCity: 'San Jose',
    primaryState: 'CA',
    telehealth: true,
    inPerson: false,
    locationDescription: 'Fully virtual practice—open worldwide',
    seoZip1: '95112',
    nearbyCity1: 'Santa Clara',
    feeIndividual: '125',
    feeCouples: null,
    slidingScale: true,
    freeConsultation: false,
    paymentMethods: ['Credit Card', 'Apple Pay'],
    insuranceAccepted: 'Out-of-network reimbursement',
    licenseStatus: 'Active',
    profession: 'Clinical Psychologist',
    licenseNumber: 'PSYD112233',
    licenseState: 'CA',
    licenseExpirationMonth: 8,
    licenseExpirationYear: 2025,
    educationSchool: 'Cal State East Bay',
    educationDegree: 'PsyD',
    educationYearGraduated: 2018,
    practiceStartYear: 2019,
    tagline: 'An affirming space for all identities',
    personalStatement1: 'I specialize in LGBTQ+ affirmative therapy.',
    personalStatement2: 'Creating safety and trust is my first priority.',
    personalStatement3: 'Let’s explore identity, relationships, and resilience.',
    issues: ['Identity', 'Coming Out', 'Depression'],
    specialtyDescription: 'Focus on queer and trans mental health.',
    mentalHealthRoles: ['Therapist'],
    sexuality: 'Queer-affirming',
    ages: ['Adult'],
    participants: ['Individual', 'Couples'],
    communities: ['LGBTQ+'],
    languages: ['English', 'Spanish'],
    topIssues: ['Identity Exploration'],
    treatmentStyle: ['Existential', 'Narrative'],
    treatmentStyleDescription: 'Existential exploration with narrative framing.',
  },
  {
    slug: 'rachel-wong',
    imageUrl: '/avatars/rachel-wong.jpg',
    published: true,
    name: 'Rachel Wong, LCSW',
    primaryCredential: 'LCSW',
    gender: 'Female',
    phone: '559-555-8989',
    workEmail: 'rachel.wong@hearthaven.com',
    website: 'https://www.hearthaven.com/rachel-wong',
    primaryCity: 'Fresno',
    primaryState: 'CA',
    telehealth: false,
    inPerson: true,
    locationDescription: 'Located near downtown Fresno',
    seoZip1: '93721',
    nearbyCity1: 'Clovis',
    feeIndividual: '110',
    slidingScale: true,
    freeConsultation: true,
    paymentMethods: ['Cash', 'Credit Card'],
    insuranceAccepted: 'Medi-Cal, Private Pay',
    licenseStatus: 'Active',
    profession: 'Licensed Clinical Social Worker',
    licenseNumber: 'LCSW334455',
    licenseState: 'CA',
    licenseExpirationMonth: 3,
    licenseExpirationYear: 2026,
    educationSchool: 'CSU Bakersfield',
    educationDegree: 'MSW',
    educationYearGraduated: 2013,
    practiceStartYear: 2014,
    tagline: 'A compassionate partner on your healing journey',
    personalStatement1: 'I center trauma-informed and client-led care.',
    personalStatement2: 'My approach is warm, empathic, and collaborative.',
    personalStatement3: 'Together we’ll find your path forward.',
    issues: ['Trauma', 'Depression'],
    specialtyDescription: 'Expert in child-parent attachment work.',
    mentalHealthRoles: ['Therapist', 'Mediator'],
    sexuality: 'All',
    ages: ['Children', 'Adolescents'],
    participants: ['Individual', 'Family'],
    communities: ['Immigrant Families'],
    languages: ['English', 'Cantonese'],
    topIssues: ['Attachment Issues'],
    treatmentStyle: ['Family Systems', 'Mindfulness'],
    treatmentStyleDescription: 'Mindful family systems therapy.',
  },
]

async function main() {
  for (const t of therapists) {
    await prisma.therapist.upsert({
      where: { slug: t.slug },
      update: {},
      create: t,
    })
  }
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
